Repository openshift/driver-toolkit, pull requests merged in 2021-06, with the labels that each got.

#25 Update Dockerfile
  Dockerfile
Labels: approved, lgtm

#26 Requirements for authenticating kernel modules with X.509 keys
  Dockerfile
Labels: approved, lgtm

#27 Update OWNERS
  OWNERS
Labels: approved, lgtm

#30 Only install mokutil on relevant architectures
  Dockerfile
Labels: approved, lgtm

#34 Rewrite architecture check for mokutil installation
  Dockerfile
Labels: approved, lgtm

#31 Install gcc in driver-toolkit
  Dockerfile
Labels: approved, lgtm

#33 Add README to driver-toolkit repository
  README.md
Labels: approved, lgtm

#35 Rearrange architecture check
  Dockerfile
Labels: approved, lgtm

#36 Fix GCC install on non-x86 and add yum clean all
  Dockerfile
Labels: approved, lgtm

#37 [release-4.8] Bug 1972676: Requirements for authenticating kernel modules with X.509 keys
  Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#38 [release 4.8] Bug 1974447: Cherry pick gcc to release 4.8
  Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#44 Bug 1977972: /etc/driver-toolkit-release.json kernel version match rpm -q output
  Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
