Repository openshift/driver-toolkit, pull requests merged in 2022-05, with the labels that each got.

#80 Updating the documentation on how to use DTK as a multi-stage image.
  README.md
Labels: approved, lgtm

#81 Add imagestream for driver-toolkit.
  manifests/01-openshift-imagestream.yaml
  manifests/image-references
Labels: approved, lgtm

#83 Replacing last layer image in driver-container documentation from ubi8 to ubi8/ubi-minimal
  README.md
Labels: approved, lgtm

#84 Bug 2087026: Adding manifests/ inside DTK container image.
  Dockerfile
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#87 Bug 2087114: Add simple-procfs-kmod in modprobe example in README.md
  README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
